### PR TITLE
Lossless image optimization

### PR DESCRIPTION
**Pull request by webimpress**
Total size 25% decreased!

Before: 15.1 MB (15,099,294 bytes)
After: 11.3 MB (11,331,842 bytes)

### CODE REVIEW

**Comment by webimpress** [comment]
I did only lossless optimization, but google in insights tools suggest even more
https://developers.google.com/speed/docs/insights/OptimizeImages

They suggested to:
- reduce quality to 85
- reduce Chroma sampling to 4:2:0

@froschdesign Do you think we should try this as well?

**Comment by froschdesign** [comment]
@webimpress 
I think lossless optimization is good and enough. No need to change to reduce the quality.

**Comment by ezimuel** [comment]
@webimpress and @froschdesign this PR is ready to be merged?

**Comment by webimpress** [comment]
@ezimuel Yes, it's ready. Just lossless optimization, as @froschdesign confirmed.

**Pull request merged**
