### PR TITLE
Fixes some HTML problems

### PR DESCRIPTION
**Pull request by froschdesign**

### CODE REVIEW

**Comment by froschdesign** [comment]
Ping @ezimuel

**Comment by ezimuel** [comment]
@froschdesign there are some conflicts. Can you check please? Thanks.

**Comment by froschdesign** [comment]
I will check this!

**Comment by ezimuel** [comment]
@froschdesign ping

**Comment by froschdesign** [comment]
@ezimuel 
I have some ugly problems at merging with this files:

**Pull request closed without merging**
